name: WKO AKS Sample Auto Workflow

on:
  push:
    branches:
      - wko_aks_sample_automation
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    # docker is pre-installed on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WKO_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run WKO automation scripts
        continue-on-error: true
        run: |          
          cd $HOME
          source $HOME/.bashrc
          sudo apt install sed
          export azureResourceUID=${{ github.run_id }}
          export namePrefix=wls
          echo "namePrefix=${namePrefix}" >> $GITHUB_ENV
          
          git clone -b update_automation_scripts_and_docs https://github.com/backwind1233/weblogic-kubernetes-operator.git
          cd $HOME/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service

          bash create-domain-on-aks.sh -u ${{ secrets.ORACLE_USERNAME }} -p ${{ secrets.ORACLE_PASSWORD }}
          
      - name: Sleep 20 minutes
        continue-on-error: true
        run: |
          sleep $((20 * 60))

      - name: Delete Resource
        run: |
          az group delete --name ${{ env.namePrefix }}resourcegroup${{ github.run_id }} --yes --no-wait
